package com.java.mapper;

public class BlogFriend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_friend.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_friend.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_friend.friend_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer friendUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_friend.id
     *
     * @return the value of blog_friend.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_friend.id
     *
     * @param id the value for blog_friend.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_friend.user_id
     *
     * @return the value of blog_friend.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_friend.user_id
     *
     * @param userId the value for blog_friend.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_friend.friend_user_id
     *
     * @return the value of blog_friend.friend_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getFriendUserId() {
        return friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_friend.friend_user_id
     *
     * @param friendUserId the value for blog_friend.friend_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setFriendUserId(Integer friendUserId) {
        this.friendUserId = friendUserId;
    }
}