package com.java.mapper;

import com.java.mapper.BlogPhoto;

public interface BlogPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_photo
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_photo
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int insert(BlogPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_photo
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int insertSelective(BlogPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_photo
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    BlogPhoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_photo
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int updateByPrimaryKeySelective(BlogPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_photo
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int updateByPrimaryKey(BlogPhoto record);
}