package com.java.mapper;

public class BlogPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_photo.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_photo.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_photo.sort_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_photo.photo_addr
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String photoAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_photo.photo_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String photoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_photo.photo_info
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String photoInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_photo.id
     *
     * @return the value of blog_photo.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_photo.id
     *
     * @param id the value for blog_photo.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_photo.user_id
     *
     * @return the value of blog_photo.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_photo.user_id
     *
     * @param userId the value for blog_photo.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_photo.sort_id
     *
     * @return the value of blog_photo.sort_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_photo.sort_id
     *
     * @param sortId the value for blog_photo.sort_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_photo.photo_addr
     *
     * @return the value of blog_photo.photo_addr
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getPhotoAddr() {
        return photoAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_photo.photo_addr
     *
     * @param photoAddr the value for blog_photo.photo_addr
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setPhotoAddr(String photoAddr) {
        this.photoAddr = photoAddr == null ? null : photoAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_photo.photo_name
     *
     * @return the value of blog_photo.photo_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_photo.photo_name
     *
     * @param photoName the value for blog_photo.photo_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_photo.photo_info
     *
     * @return the value of blog_photo.photo_info
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getPhotoInfo() {
        return photoInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_photo.photo_info
     *
     * @param photoInfo the value for blog_photo.photo_info
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setPhotoInfo(String photoInfo) {
        this.photoInfo = photoInfo == null ? null : photoInfo.trim();
    }
}