package com.java.mapper;

public class BlogType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_type.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_type.type_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_type.type_info
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String typeInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_type.id
     *
     * @return the value of blog_type.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_type.id
     *
     * @param id the value for blog_type.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_type.type_name
     *
     * @return the value of blog_type.type_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_type.type_name
     *
     * @param typeName the value for blog_type.type_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_type.type_info
     *
     * @return the value of blog_type.type_info
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getTypeInfo() {
        return typeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_type.type_info
     *
     * @param typeInfo the value for blog_type.type_info
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setTypeInfo(String typeInfo) {
        this.typeInfo = typeInfo == null ? null : typeInfo.trim();
    }
}