package com.java.mapper;

import java.util.Date;

public class BlogComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.object_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer objectUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.article_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_detail
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String commentDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Date commentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.id
     *
     * @return the value of blog_comment.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.id
     *
     * @param id the value for blog_comment.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.user_id
     *
     * @return the value of blog_comment.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.user_id
     *
     * @param userId the value for blog_comment.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.object_user_id
     *
     * @return the value of blog_comment.object_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getObjectUserId() {
        return objectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.object_user_id
     *
     * @param objectUserId the value for blog_comment.object_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setObjectUserId(Integer objectUserId) {
        this.objectUserId = objectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.article_id
     *
     * @return the value of blog_comment.article_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.article_id
     *
     * @param articleId the value for blog_comment.article_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_detail
     *
     * @return the value of blog_comment.comment_detail
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getCommentDetail() {
        return commentDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_detail
     *
     * @param commentDetail the value for blog_comment.comment_detail
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCommentDetail(String commentDetail) {
        this.commentDetail = commentDetail == null ? null : commentDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_time
     *
     * @return the value of blog_comment.comment_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_time
     *
     * @param commentTime the value for blog_comment.comment_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }
}