package com.java.mapper;

import java.util.Date;

public class BlogMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_message.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_message.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_message.object_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer objectUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_message.message_title
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer messageTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_message.message_detail
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String messageDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_message.message_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Date messageTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_message.id
     *
     * @return the value of blog_message.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_message.id
     *
     * @param id the value for blog_message.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_message.user_id
     *
     * @return the value of blog_message.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_message.user_id
     *
     * @param userId the value for blog_message.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_message.object_user_id
     *
     * @return the value of blog_message.object_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getObjectUserId() {
        return objectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_message.object_user_id
     *
     * @param objectUserId the value for blog_message.object_user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setObjectUserId(Integer objectUserId) {
        this.objectUserId = objectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_message.message_title
     *
     * @return the value of blog_message.message_title
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_message.message_title
     *
     * @param messageTitle the value for blog_message.message_title
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setMessageTitle(Integer messageTitle) {
        this.messageTitle = messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_message.message_detail
     *
     * @return the value of blog_message.message_detail
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getMessageDetail() {
        return messageDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_message.message_detail
     *
     * @param messageDetail the value for blog_message.message_detail
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setMessageDetail(String messageDetail) {
        this.messageDetail = messageDetail == null ? null : messageDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_message.message_time
     *
     * @return the value of blog_message.message_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Date getMessageTime() {
        return messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_message.message_time
     *
     * @param messageTime the value for blog_message.message_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setMessageTime(Date messageTime) {
        this.messageTime = messageTime;
    }
}