package com.java.mapper;

import com.java.mapper.BlogMessage;

public interface BlogMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int insert(BlogMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int insertSelective(BlogMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    BlogMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int updateByPrimaryKeySelective(BlogMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_message
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int updateByPrimaryKey(BlogMessage record);
}