package com.java.mapper;

import com.java.mapper.BlogType;

public interface BlogTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int insert(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int insertSelective(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    BlogType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int updateByPrimaryKeySelective(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    int updateByPrimaryKey(BlogType record);
}