package com.java.mapper;

import java.util.Date;

public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.site_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.category
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Date logTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.ip
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.url
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.title
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.content
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_id
     *
     * @return the value of sys_log.log_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_id
     *
     * @param logId the value for sys_log.log_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.site_id
     *
     * @return the value of sys_log.site_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.site_id
     *
     * @param siteId the value for sys_log.site_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.category
     *
     * @return the value of sys_log.category
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.category
     *
     * @param category the value for sys_log.category
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_time
     *
     * @return the value of sys_log.log_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_time
     *
     * @param logTime the value for sys_log.log_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.ip
     *
     * @return the value of sys_log.ip
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.ip
     *
     * @param ip the value for sys_log.ip
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.url
     *
     * @return the value of sys_log.url
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.url
     *
     * @param url the value for sys_log.url
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.title
     *
     * @return the value of sys_log.title
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.title
     *
     * @param title the value for sys_log.title
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.content
     *
     * @return the value of sys_log.content
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.content
     *
     * @param content the value for sys_log.content
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}