package com.java.mapper;

import java.util.Date;

public class SysPrivilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_privilege.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_privilege.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_privilege.privilege_value
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer privilegeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_privilege.create_by
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_privilege.create_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.id
     *
     * @return the value of sys_privilege.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.id
     *
     * @param id the value for sys_privilege.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.user_id
     *
     * @return the value of sys_privilege.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.user_id
     *
     * @param userId the value for sys_privilege.user_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.privilege_value
     *
     * @return the value of sys_privilege.privilege_value
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getPrivilegeValue() {
        return privilegeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.privilege_value
     *
     * @param privilegeValue the value for sys_privilege.privilege_value
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setPrivilegeValue(Integer privilegeValue) {
        this.privilegeValue = privilegeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.create_by
     *
     * @return the value of sys_privilege.create_by
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.create_by
     *
     * @param createBy the value for sys_privilege.create_by
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.create_time
     *
     * @return the value of sys_privilege.create_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.create_time
     *
     * @param createTime the value for sys_privilege.create_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}