package com.java.mapper;

import java.util.Date;

public class SysUserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.group_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.group_privilege
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Integer groupPrivilege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.group_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.create_by
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.create_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.id
     *
     * @return the value of sys_user_group.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.id
     *
     * @param id the value for sys_user_group.id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.group_id
     *
     * @return the value of sys_user_group.group_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.group_id
     *
     * @param groupId the value for sys_user_group.group_id
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.group_privilege
     *
     * @return the value of sys_user_group.group_privilege
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Integer getGroupPrivilege() {
        return groupPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.group_privilege
     *
     * @param groupPrivilege the value for sys_user_group.group_privilege
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setGroupPrivilege(Integer groupPrivilege) {
        this.groupPrivilege = groupPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.group_name
     *
     * @return the value of sys_user_group.group_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.group_name
     *
     * @param groupName the value for sys_user_group.group_name
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.create_by
     *
     * @return the value of sys_user_group.create_by
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.create_by
     *
     * @param createBy the value for sys_user_group.create_by
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.create_time
     *
     * @return the value of sys_user_group.create_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.create_time
     *
     * @param createTime the value for sys_user_group.create_time
     *
     * @mbg.generated Thu Mar 22 11:54:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}